### PR TITLE
Add nixpkgs package to readme

### PR DESCRIPTION
**Pull request by elkowar**
This PR documents the nix package for fet.sh in the readme

### CODE REVIEW

**Comment by MatthiasCoppens** [comment]
Repology merged the projects fet.sh, fet-sh and fetsh to fet.sh, so we can maybe use one of the [badges](https://repology.org/project/fet.sh/badges), for example:
[Packaging status](https://repology.org/project/fet.sh/versions)

**Comment by elkowar** [comment]
the badges sound like a really nice idea

**Comment by 6gk** [comment]
@MatthiasCoppens Honestly I think badges are very ugly.

**Comment by Joebortscheller** [comment]
Ya! To the badges! 

Joseph Bortscheller

**Comment by 6gk** [comment]
If there's a way to make the badges not look like they were pulled from 2002, please let me know and maybe I will consider adding them.

**Comment by MatthiasCoppens** [comment]
Something like this is a bit sleeker, but contains less information:
[Packaging status](https://repology.org/project/fet.sh/versions)

**Comment by 6gk** [comment]
That is still really ugly.

I mean the colours / gradient, not the info.

**Pull request merged**
